language: cpp
dist: bionic

jobs:
  include:
  - compiler: clang
    os: linux
  - compiler: gcc
    os: linux
  - compiler: gcc-7
    os: linux
  - compiler: gcc-8
    os: linux
  - compiler: gcc-9
    os: linux
  - compiler: gcc-10
    os: linux
  - compiler: clang
    os: osx
    osx_image: xcode11.4
  - compiler: gcc
    os: osx
    osx_image: xcode11.4

addons:
  apt:
    sources:
    - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
    - autoconf-archive
    - gcc-7
    - gcc-8
    - gcc-9
    - gcc-10
    - libc++-dev
    - libc++abi-dev
  homebrew:
    packages:
    - gettext
    - autoconf-archive

before_script:
    - ./.travis/bootstrap.sh

script:
    # Workaround Travis' clang not finding its headers.
    - if [[ $TRAVIS_OS_NAME == 'linux' && $CXX == 'clang++' ]]; then export CXX='clang++ -stdlib=libc++'; fi
    - ./configure
    - make
    - make check
    - ./test2_libxls test/files/test2.xls
